version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9100:9000'   # <== changed
      - '9101:9001'   # Console stays the same
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - shared_network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    networks:
      - shared_network

  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - '8080:8080'
    volumes:
      - ./pgadmin-data:/pgadmin4/servers.json
    networks:
      - shared_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
    restart: always
    networks:
      - shared_network

  flower:
    build:
      context: ../
    container_name: flower
    command: celery --broker=redis://redis:6379/0 flower
    restart: always
    ports:
      - '5555:5555'
    volumes:
      - ./flower-data:/app
    networks:
      - shared_network
    environment:
      FLOWER_UNAUTHENTICATED_API: true

networks:
  shared_network:
    external: true
