"""add account id to video

Revision ID: 0a8bec2c086f
Revises: b26c4e7a6dfe
Create Date: 2024-09-20 11:54:41.217144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0a8bec2c086f'
down_revision: Union[str, None] = 'b26c4e7a6dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('videos', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'videos', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'account_id')
    # ### end Alembic commands ###
