"""Change VideoEvents to reference video_id instead of event_id

Revision ID: 0b1d61c7381b
Revises: 079f7674c138
Create Date: 2025-03-08 19:27:19.377210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1d61c7381b'
down_revision: Union[str, None] = '079f7674c138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_events', sa.Column('video_id', sa.Integer(), nullable=False))
    op.drop_constraint('video_events_event_id_fkey', 'video_events', type_='foreignkey')
    op.create_foreign_key(None, 'video_events', 'videos', ['video_id'], ['id'])
    op.drop_column('video_events', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_events', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video_events', type_='foreignkey')
    op.create_foreign_key('video_events_event_id_fkey', 'video_events', 'events', ['event_id'], ['id'])
    op.drop_column('video_events', 'video_id')
    # ### end Alembic commands ###
