"""Add time_string field to VideoEvents

Revision ID: c37086b47dcf
Revises: 0b1d61c7381b
Create Date: 2025-03-08 20:44:00.087188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37086b47dcf'
down_revision: Union[str, None] = '0b1d61c7381b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_events', sa.Column('time_string', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_events', 'time_string')
    # ### end Alembic commands ###
